### ISSUE TITLE
Entries in text field not possible when only using keyboard (BITV 2.1.1a)

### ISSUE THREAD

**Issue by VivienDZB** [slidewiki/slidewiki-platform#1172]
Although the text field below the slide title can be focussed with the keyboard, no entries in this area are possible. Text can only be added in the title area (Editing a slide: https://slidewiki.org/deck/127411/_/slide/836159-1/836159-1:1/edit?language=de).

![grafik](https://user-images.githubusercontent.com/48785136/58859623-752daa00-86aa-11e9-8157-4b0d940708d9.png)

**Comment by aoelen** [comment]
It should be possible to access this text field by using the arrow keys (press the down key when the title is focussed). Can you confirm it is working?

**Comment by VivienDZB** [comment]
Sorry for answering late. Unfortunately it is not working. I still can´t reach this area to edit it.

**Comment by VivienDZB** [comment]
As far as I´m concerned it´s not possible to add any videos here...or at least I don´t know how. So here is the screen recording I made which shows the problem quite well. I´m navigading with the TAB-key to the text field below the title. As you can see, the area is focussed, but when I try to write something the title is edited. @aoelen 

https://drive.google.com/file/d/11ckL4G3xnzNwlSXcC3gYvvCoOz6frUkh/view?usp=sharing

**Comment by aoelen** [comment]
I was indeed able to reproduce this problem. But after using the arrows keys (both left,right,up,down) I was able to enter text in this field. But I agree, this is not a nice user experience. After this issue was created, the Markdown editor is introduced to provide a more accessible alternative for slide editing. So I suggest to close this issue, is that ok?
