### ISSUE TITLE
"Speaker notes"-buttons not reachable via keyboard (2.1.1a)

### ISSUE THREAD

**Issue by VivienDZB** [slidewiki/slidewiki-platform#1173]
Text editing buttons in the "Speaker note" area can not be reached with the keyboard (https://slidewiki.org/deck/127411/_/slide/836159-2/836159-2:1/edit?language=de).

![grafik](https://user-images.githubusercontent.com/48785136/58873959-cf893380-86c7-11e9-996e-ba297a9707c1.png)

**Comment by aoelen** [comment]
- Copied from #1171 -

It is possible to focus the toolbar by pressing the keyboard combination `Alt + F10`. This is done because of how the buttons behave. It is only useful to click on those buttons when a piece of text is selected, only then you can apply a style to the style. So the workflow for keyboard access is:

- Navigate to the textarea
- Select a piece of text that needs to be styled
- Press `Alt + F10` to access the toolbar
- Navigate in the toolbar between items via the arrow keys, navigate between groups via Tab key

This shortcut is currently described in the help dialog that can be viewed from: Slide editor > Add > Help (the last item). Maybe the help button should be made more visible.

I closed this issue, if you don't agree feel free to reopen!

**Comment by VivienDZB** [comment]
Works! Thank you. :)
